create table
  public.customer (
    customer_id bigint generated by default as identity,
    name character varying null,
    weight bigint null,
    height bigint null,
    constraint customer_pkey primary key (customer_id)
  ) tablespace pg_default;

create table
  public.goals (
    goal_id bigint generated by default as identity,
    type character varying null default ''::character varying,
    goal character varying null default ''::character varying,
    customer_id bigint null,
    daily_calories bigint null default '0'::bigint,
    constraint goals_pkey primary key (goal_id),
    constraint goals_customer_id_fkey foreign key (customer_id) references customer (customer_id)
  ) tablespace pg_default;

create table
  public.ingredient (
    ingredient_id bigint generated by default as identity,
    name character varying null,
    constraint ingredient_pkey primary key (ingredient_id)
  ) tablespace pg_default;

create table
  public.meal (
    meal_id bigint generated by default as identity,
    time timestamp with time zone not null default now(),
    name character varying null,
    calories bigint null default '0'::bigint,
    ingredient_id bigint null,
    customer_id bigint null,
    type text null,
    constraint meal_pkey primary key (meal_id),
    constraint meal_customer_id_fkey foreign key (customer_id) references customer (customer_id),
    constraint meal_ingredient_id_fkey foreign key (ingredient_id) references ingredient (ingredient_id)
  ) tablespace pg_default;

create table
  public.muscle_groups (
    muscle_group_id bigint generated by default as identity,
    type character varying null,
    "group" character varying null,
    constraint muscle_groups_pkey primary key (muscle_group_id)
  ) tablespace pg_default;

create table
  public.workout (
    workout_id bigint generated by default as identity,
    time timestamp with time zone not null default now(),
    calories bigint null default '0'::bigint,
    muscle_groups bigint null,
    customer_id bigint null,
    constraint Workout_pkey primary key (workout_id),
    constraint workout_customer_id_fkey foreign key (customer_id) references customer (customer_id)
  ) tablespace pg_default;
