-- REQUIRES PRE-POPULATED DATA

create table
  public.customer (
    customer_id bigint generated by default as identity,
    name character varying null,
    weight bigint null,
    height bigint null,
    constraint customer_pkey primary key (customer_id)
  ) tablespace pg_default;

create table
  public.customer_workouts (
    workout_id bigint generated by default as identity,
    exercise_id bigint not null,
    sets integer null default 0,
    reps integer null default 0,
    length integer null default 0,
    customer_id bigint not null,
    time date not null default now(),
    constraint Workout_pkey primary key (workout_id),
    constraint customer_workouts_exercise_id_fkey foreign key (exercise_id) references exercises (id),
    constraint workout_customer_id_fkey foreign key (customer_id) references customer (customer_id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.exercises (
    id bigint generated by default as identity,
    name text null,
    muscle_group_id bigint null,
    constraint exercises_pkey primary key (id),
    constraint exercises_muscle_group_id_fkey foreign key (muscle_group_id) references muscle_groups (muscle_group_id)
  ) tablespace pg_default;
-- FOR EXERCISES TABLE ON SUPABASE ONCE CREATED NAVITAGE TO Insert > Import data from CSV > Select exercises_rows (1).csv

create table
  public.goals (
    goal_id bigint generated by default as identity,
    type character varying null default ''::character varying,
    goal character varying null default ''::character varying,
    customer_id bigint null,
    daily_calories bigint null default '0'::bigint,
    constraint goals_pkey primary key (goal_id),
    constraint goals_customer_id_fkey foreign key (customer_id) references customer (customer_id)
  ) tablespace pg_default;

create table
  public.meal (
    meal_id bigint generated by default as identity,
    time timestamp with time zone not null default now(),
    name character varying null,
    calories bigint null default '0'::bigint,
    ingredient_id bigint null,
    customer_id bigint null,
    type text null,
    constraint meal_pkey primary key (meal_id),
    constraint meal_customer_id_fkey foreign key (customer_id) references customer (customer_id),
    constraint meal_ingredient_id_fkey foreign key (ingredient_id) references ingredient (ingredient_id)
  ) tablespace pg_default;

create table
  public.ingredient (
    ingredient_id bigint generated by default as identity,
    name character varying null,
    constraint ingredient_pkey primary key (ingredient_id)
  ) tablespace pg_default;

create table
  public.muscle_groups (
    muscle_group_id bigint generated by default as identity,
    type character varying null,
    "group" character varying null,
    constraint muscle_groups_pkey primary key (muscle_group_id)
  ) tablespace pg_default;
-- FOR MUSCLE GROUPS TABLE ON SUPABASE ONCE CREATED NAVITAGE TO Insert > Import data from CSV > Select muscle_groups_rows.csv
